# Generated by Django 5.0.6 on 2025-01-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomlisting'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomListing',
            new_name='RoomListingPage',
        ),
    ]
