# Generated by Django 5.0.6 on 2025-01-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomdetailpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
