# Generated by Django 5.0.6 on 2025-01-28 12:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_form_button_text_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_section_body',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section_cta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='About CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
