# Generated by Django 5.0.6 on 2025-01-28 12:15

import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_about_section_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_section_images',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_section_body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
