# Generated by Django 5.0.6 on 2025-01-28 12:35

import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_about_section_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeheroimagerel',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='homeheroimagerel',
            name='page',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_images',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.DeleteModel(
            name='HeroImage',
        ),
        migrations.DeleteModel(
            name='HomeHeroImageRel',
        ),
    ]
