# Generated by Django 5.0.6 on 2025-01-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_section_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
