# Generated by Django 5.0.6 on 2025-01-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_testimonial_homepage_testimonial_section_heading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='review',
            new_name='text',
        ),
    ]
