# Generated by Django 5.0.6 on 2025-01-30 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_genericsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericSettings',
        ),
    ]
