# Generated by Django 5.0.6 on 2025-01-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_about_section_images_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
