# Generated by Django 5.0.6 on 2025-01-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericsettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='genericsettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='genericsettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='genericsettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='genericsettings',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='genericsettings',
            name='x_url',
        ),
        migrations.AddField(
            model_name='genericsettings',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='genericsettings',
            name='organisation_url',
            field=models.URLField(blank=True, verbose_name='Organisation URL'),
        ),
        migrations.AddField(
            model_name='genericsettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter URL'),
        ),
    ]
