# Generated by Django 5.0.6 on 2025-01-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_genericsettings_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericSettings',
        ),
    ]
