# Generated by Django 5.0.6 on 2025-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_in',
            field=models.DateField(null=True, verbose_name='Check In'),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_out',
            field=models.DateField(null=True, verbose_name='Check Out'),
        ),
    ]
